---
title: "Курсовая работа"
author: "Изотов Илья, Куштанов Дмитрий РИ-450004"
---

```{r}
options(scipen=10000)
data <- read.csv("kc_house_data.csv", header=TRUE, sep=",")
head(data)
summary(data)
data <- data[,-c(1,2)]
data$waterfront <- factor(data$waterfront, levels = c(0,1))
levels(data$waterfront) <- c("No", "Yes")
hist(data$price, xlab = "Цена",  main = "Цена")
hist(data$sqft_living, xlab = "Размер жилой площади", main = "Жилая площадь")
hist(data$yr_built, xlab = "Год постройки", main = "Год постройки")
```


###Визулизируем возможные зависимости

```{R}
plot(data$price, data$sqft_living,'p',main = "Зависимость стоимости от размера жилой площади")
plot(data$price, data$grade,'p',main = "Зависимость стоимости от оценки")
plot(data$waterfront, data$price,'p',main = "Зависимость стоимости от наличия вида на набережную")
```

###Очистка от выбросов

```{r}
summary(data[data$waterfront=="No", ]$price)
data <- data[data$sqft_living<13000,]
data<- data[data$price<2*10^6,]
data <- data[!(data$price>4*10^6 & data$waterfront=="Yes"), ]
plot(data$waterfront, data$price,'p',main = "Зависимость стоимости от наличия вида на набережную")
plot(sort(data$price))
```

###Нахождение значимых параметров

```{r}
boxplot(data$price)
lm.data <- lm(price~., data = data)
summary(lm.data)
plot(lm.data)
```

```{R}
plot(x= data$price, xlab = "Цена", ylab = "Размер жилой площади", y = data$sqft_living,'p',main = "Зависимость стоимости от размера жилой площади")
plot(x= data$price,xlab = "Цена", ylab = "Оценка", y =data$grade,'p',main = "Зависимость стоимости от оценки")
plot(data$waterfront, data$price,'p',main = "Зависимость стоимости от наличия вида на набережную")
```

###Добавление дополнительного параметра средней цены по почтовому индексу и разделение данных

```{r}
data$avgZipCodePrice <- ave(data$price,data$zipcode)
odds <- seq(1, nrow(data), by=2)
data.in <- data[odds, ]
data.out <- data[-odds, ]
```

###Тренировка первой модели

```{r}
lm.data.in <- lm(price~sqft_living+waterfront+floors+view+condition+yr_built+grade+bedrooms+bathrooms+lat+long+sqft_living15+avgZipCodePrice, data = data.in)
data.predict.out <- predict(lm.data.in, data.out)
cor(data.out$price, data.predict.out)
summary(lm.data.in)
plot(x = data.out$price, xlab = "Цена", ylab = "Предсказанная цена",y =  data.predict.out, main = "Зависимость проверяемых цен от предсказанных")
hist(data.out$price - data.predict.out, xlab = "Разница цен", main = "Гистограмма разницы предсказания")
```


###Уменьшение числа параметров для тренировки второй модели

```{r}
lm.data.in1 <- lm(price~sqft_living+yr_built+grade+waterfront+avgZipCodePrice, data = data.in)
data.predict.out1 <- predict(lm.data.in1, data.out)
cor(data.out$price, data.predict.out1)
summary(lm.data.in1)
plot(x = data.out$price, xlab = "Цена", ylab = "Предсказанная цена",y =  data.predict.out1, main = "Зависимость проверяемых цен от предсказанных")
hist(data.out$price - data.predict.out1, xlab = "Разница цен", main = "Гистограмма разницы предсказания")
plot(lm.data.in1)
```
