# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1071, 464)
        MainWindow.setMaximumSize(QtCore.QSize(1071, 464))
        font = QtGui.QFont()
        font.setPointSize(12)
        MainWindow.setFont(font)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(1071, 430))
        self.centralwidget.setMaximumSize(QtCore.QSize(1071, 430))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(30, 30, 1011, 231))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.gridLayoutWidget_2)
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.spinBoxSqftLiving = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.spinBoxSqftLiving.setMinimum(200)
        self.spinBoxSqftLiving.setMaximum(8000)
        self.spinBoxSqftLiving.setProperty("value", 1000)
        self.spinBoxSqftLiving.setObjectName("spinBoxSqftLiving")
        self.gridLayout_4.addWidget(self.spinBoxSqftLiving, 1, 1, 1, 1)
        self.spinBoxGrade = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxGrade.sizePolicy().hasHeightForWidth())
        self.spinBoxGrade.setSizePolicy(sizePolicy)
        self.spinBoxGrade.setMinimum(1)
        self.spinBoxGrade.setMaximum(13)
        self.spinBoxGrade.setProperty("value", 5)
        self.spinBoxGrade.setObjectName("spinBoxGrade")
        self.gridLayout_4.addWidget(self.spinBoxGrade, 3, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 2, 0, 1, 1)
        self.spinBoxYrBuilt = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.spinBoxYrBuilt.setMinimum(1900)
        self.spinBoxYrBuilt.setMaximum(2015)
        self.spinBoxYrBuilt.setProperty("value", 1950)
        self.spinBoxYrBuilt.setObjectName("spinBoxYrBuilt")
        self.gridLayout_4.addWidget(self.spinBoxYrBuilt, 2, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 70))
        self.groupBox.setFlat(True)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 30, 281, 30))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.verticalLayoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.radioButtonNo = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButtonNo.setChecked(True)
        self.radioButtonNo.setObjectName("radioButtonNo")
        self.horizontalLayout_3.addWidget(self.radioButtonNo)
        self.radioButtonYes = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButtonYes.setObjectName("radioButtonYes")
        self.horizontalLayout_3.addWidget(self.radioButtonYes)
        self.gridLayout_4.addWidget(self.groupBox, 0, 0, 1, 2)
        self.horizontalLayout_2.addLayout(self.gridLayout_4)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.listZip = QtWidgets.QListWidget(self.gridLayoutWidget_2)
        self.listZip.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listZip.sizePolicy().hasHeightForWidth())
        self.listZip.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.listZip.setFont(font)
        self.listZip.setObjectName("listZip")
        self.verticalLayout_2.addWidget(self.listZip)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 280, 1011, 131))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonPredict = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonPredict.sizePolicy().hasHeightForWidth())
        self.pushButtonPredict.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.pushButtonPredict.setFont(font)
        self.pushButtonPredict.setObjectName("pushButtonPredict")
        self.horizontalLayout.addWidget(self.pushButtonPredict)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.lcdNumberResult = QtWidgets.QLCDNumber(self.horizontalLayoutWidget)
        self.lcdNumberResult.setDigitCount(10)
        self.lcdNumberResult.setMode(QtWidgets.QLCDNumber.Dec)
        self.lcdNumberResult.setProperty("intValue", 1225000)
        self.lcdNumberResult.setObjectName("lcdNumberResult")
        self.horizontalLayout.addWidget(self.lcdNumberResult)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1071, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.listZip.setCurrentRow(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.pushButtonPredict, self.spinBoxSqftLiving)
        MainWindow.setTabOrder(self.spinBoxSqftLiving, self.spinBoxYrBuilt)
        MainWindow.setTabOrder(self.spinBoxYrBuilt, self.spinBoxGrade)
        MainWindow.setTabOrder(self.spinBoxGrade, self.listZip)
        MainWindow.setTabOrder(self.listZip, self.radioButtonNo)
        MainWindow.setTabOrder(self.radioButtonNo, self.radioButtonYes)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Предсказать стоимость дома"))
        self.label.setText(_translate("MainWindow", "Жилая площадь"))
        self.label_3.setText(_translate("MainWindow", "Оценка"))
        self.label_2.setText(_translate("MainWindow", "Год постройки"))
        self.groupBox.setTitle(_translate("MainWindow", "Расположение на набережной:"))
        self.radioButtonNo.setText(_translate("MainWindow", "Нет"))
        self.radioButtonYes.setText(_translate("MainWindow", "Да"))
        self.label_4.setText(_translate("MainWindow", "Индекс:"))
        self.listZip.setSortingEnabled(True)
        self.pushButtonPredict.setText(_translate("MainWindow", "Предсказать"))

